auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: USERNAME
    password: PASSWORD
images:
  gcr.io/distroless/static: registry.cn-hangzhou.aliyuncs.com/synchub/static
  k8s.gcr.io/etcd: registry.cn-hangzhou.aliyuncs.com/synchub/etcd
  
  
