auth:
  #registry.cn-hangzhou.aliyuncs.com:
  registry.cn-guangzhou.aliyuncs.com:
    username: USERNAME
    password: PASSWORD
images:
  registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.13.0: registry.cn-guangzhou.aliyuncs.com/synchub/kube-state-metrics
  #gocrane/craned:v0.11.0,pr-839-fb1c0ce: registry.cn-guangzhou.aliyuncs.com/synchub/gocrane-craned
  #gocrane/dashboard:v0.11.0,pr-839-fb1c0ce: registry.cn-guangzhou.aliyuncs.com/synchub/gocrane-dashboard
  #sealio/walrus:v0.6.0: registry.cn-guangzhou.aliyuncs.com/synchub/walrus
  #node:22.12-alpine: registry.cn-guangzhou.aliyuncs.com/synchub/node
  #python:3.10-slim-bookworm,3.12-slim-bookworm: registry.cn-guangzhou.aliyuncs.com/synchub/python
  #ghcr.io/astral-sh/uv:python3.10-bookworm-slim,python3.12-bookworm-slim: registry.cn-guangzhou.aliyuncs.com/synchub/uv
  #cylab/wrk2: registry.cn-guangzhou.aliyuncs.com/synchub/wrk2
  #nacos/nacos-server:2.0.6: registry.cn-guangzhou.aliyuncs.com/synchub/nacos
  #node:20-alpine: registry.cn-guangzhou.aliyuncs.com/synchub/node
  #grafana/grafana:11.5.2,11.3.4: registry.cn-hangzhou.aliyuncs.com/synchub/grafana
  #oamdev/terraform-controller: registry.cn-hangzhou.aliyuncs.com/synchub/oamdev-terraform-controller
  #fluxcd/helm-controller: registry.cn-hangzhou.aliyuncs.com/synchub/fluxcd-helm-controller
  #fluxcd/source-controller: registry.cn-hangzhou.aliyuncs.com/synchub/fluxcd-source-controller
  #fluxcd/image-automation-controller: registry.cn-hangzhou.aliyuncs.com/synchub/fluxcd-image-automation-controller
  #fluxcd/image-reflector-controller: registry.cn-hangzhou.aliyuncs.com/synchub/fluxcd-image-reflector-controller
  #fluxcd/kustomize-controller: registry.cn-hangzhou.aliyuncs.com/synchub/fluxcd-kustomize-controller
  #oamdev/velaux: registry.cn-hangzhou.aliyuncs.com/synchub/oamdev-velaux
  #oamdev/vela-core: registry.cn-hangzhou.aliyuncs.com/synchub/oamdev-vela-core
  #oamdev/cluster-gateway: registry.cn-hangzhou.aliyuncs.com/synchub/oamdev-cluster-gateway
  #oamdev/hello-world: registry.cn-hangzhou.aliyuncs.com/synchub/oamdev-hello-world
  #oamdev/alpine-k8s: registry.cn-hangzhou.aliyuncs.com/synchub/oamdev-alpine-k8s
  #oamdev/kube-webhook-certgen: registry.cn-hangzhou.aliyuncs.com/synchub/oamdev-kube-webhook-certgen
  #bitnami/redis: registry.cn-hangzhou.aliyuncs.com/synchub/redis
  #whyour/qinglong: registry.cn-hangzhou.aliyuncs.com/synchub/qinglong
  #pnnlmiscscripts/xmlstarlet: registry.cn-hangzhou.aliyuncs.com/synchub/xmlstarlet
  #emqx/emqx: registry.cn-hangzhou.aliyuncs.com/synchub/emqx
  #registry-1.docker.io/bitnami/mongodb: registry.cn-hangzhou.aliyuncs.com/synchub/mongodb
  #radial/busyboxplus: registry.cn-hangzhou.aliyuncs.com/synchub/busyboxplus
  #public.ecr.aws/zinclabs/openobserve: registry.cn-hangzhou.aliyuncs.com/synchub/openobserve
  #golang: registry.cn-hangzhou.aliyuncs.com/synchub/golang
  #tdengine/tdengine: registry.cn-hangzhou.aliyuncs.com/synchub/tdengine
  #nicolaka/netshoot: registry.cn-hangzhou.aliyuncs.com/synchub/nicolaka-netshoot
  #apachesuperset.docker.scarf.sh/apache/superset: registry.cn-hangzhou.aliyuncs.com/synchub/apache-superset
  #docker.io/istio/examples-bookinfo-details-v1: registry.cn-hangzhou.aliyuncs.com/synchub/istio-examples-bookinfo-details-v1
  #docker.io/istio/examples-bookinfo-reviews-v1: registry.cn-hangzhou.aliyuncs.com/synchub/istio-examples-bookinfo-reviews-v1
  #docker.io/istio/examples-bookinfo-reviews-v2: registry.cn-hangzhou.aliyuncs.com/synchub/istio-examples-bookinfo-reviews-v2
  #docker.io/istio/examples-bookinfo-reviews-v3: registry.cn-hangzhou.aliyuncs.com/synchub/istio-examples-bookinfo-reviews-v3
  #docker.io/istio/examples-bookinfo-productpage-v1: registry.cn-hangzhou.aliyuncs.com/synchub/istio-examples-bookinfo-productpage-v1
  #docker.io/istio/examples-bookinfo-ratings-v1: registry.cn-hangzhou.aliyuncs.com/synchub/istio-examples-bookinfo-ratings-v1
  #registry.k8s.io/prometheus-adapter/prometheus-adapter: registry.cn-hangzhou.aliyuncs.com/synchub/prometheus-adapter
  #gcr.io/bank-of-anthos/accounts-db: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-accounts-db
  #gcr.io/bank-of-anthos/balancereader: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-balancereader
  #gcr.io/bank-of-anthos/contacts: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-contacts
  #gcr.io/bank-of-anthos/frontend: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-frontend
  #gcr.io/bank-of-anthos/ledger-db: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-ledger-db
  #gcr.io/bank-of-anthos/ledgerwriter: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-ledgerwriter
  #gcr.io/bank-of-anthos/loadgenerator: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-loadgenerator
  #gcr.io/bank-of-anthos/transactionhistory: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-transactionhistory
  #gcr.io/bank-of-anthos/userservice: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-userservice
  #us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/accounts-db: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-accounts-db
  #us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/balancereader: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-balancereader
  #us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/contacts: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-contacts
  #us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/frontend: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-frontend
  #us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/ledger-db: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-ledger-db
  #us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/ledgerwriter: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-ledgerwriter
  #us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/loadgenerator: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-loadgenerator
  #us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/transactionhistory: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-transactionhistory
  #us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/userservice: registry.cn-hangzhou.aliyuncs.com/synchub/bank-of-anthos-userservice
  #ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator: registry.cn-hangzhou.aliyuncs.com/synchub/opentelemetry-operator
  #ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java: registry.cn-hangzhou.aliyuncs.com/synchub/autoinstrumentation-java
  #ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs: registry.cn-hangzhou.aliyuncs.com/synchub/autoinstrumentation-nodejs
  #ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python: registry.cn-hangzhou.aliyuncs.com/synchub/autoinstrumentation-python
  #ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet: registry.cn-hangzhou.aliyuncs.com/synchub/autoinstrumentation-dotnet
  #ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-go: registry.cn-hangzhou.aliyuncs.com/synchub/autoinstrumentation-go
  #otel/opentelemetry-collector-contrib: registry.cn-hangzhou.aliyuncs.com/synchub/opentelemetry-collector-contrib
  #elasticsearch: registry.cn-hangzhou.aliyuncs.com/synchub/elasticsearch
  #nginx: registry.cn-hangzhou.aliyuncs.com/synchub/nginx
  #kibana: registry.cn-hangzhou.aliyuncs.com/synchub/kibana
  #mysql: registry.cn-hangzhou.aliyuncs.com/synchub/mysql
  #prom/mysqld-exporter: registry.cn-hangzhou.aliyuncs.com/synchub/prom-mysqld-exporter
  #otel/opentelemetry-collector: registry.cn-hangzhou.aliyuncs.com/synchub/otel-opentelemetry-collector
  #gcr.io/kubebuilder/kube-rbac-proxy: registry.cn-hangzhou.aliyuncs.com/synchub/kube-rbac-proxy
  #registry.k8s.io/kube-state-metrics/kube-state-metrics: registry.cn-hangzhou.aliyuncs.com/synchub/kube-state-metrics
  #registry.k8s.io/ingress-nginx/kube-webhook-certgen: registry.cn-hangzhou.aliyuncs.com/synchub/kube-webhook-certgen
  #thingsboard/tb-gateway: registry.cn-hangzhou.aliyuncs.com/synchub/tb-gateway
  #thingsboard/tb-coap-transport: registry.cn-hangzhou.aliyuncs.com/synchub/tb-coap-transport
  #thingsboard/tb-http-transport: registry.cn-hangzhou.aliyuncs.com/synchub/tb-http-transport
  #thingsboard/tb-node: registry.cn-hangzhou.aliyuncs.com/synchub/tb-node
  #thingsboard/tb-js-executor: registry.cn-hangzhou.aliyuncs.com/synchub/tb-js-executor
  #thingsboard/tb-web-ui: registry.cn-hangzhou.aliyuncs.com/synchub/tb-web-ui
  #thingsboard/tb-mqtt-transport: registry.cn-hangzhou.aliyuncs.com/synchub/tb-mqtt-transport
  #bitnami/kafka: registry.cn-hangzhou.aliyuncs.com/synchub/kafka
  #bitnami/pgpool: registry.cn-hangzhou.aliyuncs.com/synchub/pgpool
  #bitnami/postgresql-repmgr: registry.cn-hangzhou.aliyuncs.com/synchub/postgresql-repmgr
  #bitnami/redis: registry.cn-hangzhou.aliyuncs.com/synchub/redis
  #bitnami/zookeeper: registry.cn-hangzhou.aliyuncs.com/synchub/zookeeper
  #quay.io/argoproj/argo-rollouts: registry.cn-hangzhou.aliyuncs.com/synchub/argo-rollouts
  #gcr.io/distroless/static: registry.cn-hangzhou.aliyuncs.com/synchub/static
  #k8s.gcr.io/etcd: registry.cn-hangzhou.aliyuncs.com/synchub/etcd
  #k8s.gcr.io/node-problem-detector/node-problem-detector: registry.cn-hangzhou.aliyuncs.com/synchub/node-problem-detector
  #kubesphere/kube-proxy: registry.cn-hangzhou.aliyuncs.com/synchub/kube-proxy
  
